export default {
    CHANGE_PHONE: 'CHANGE_PHONE',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_START: 'LOGIN_START',
    GET_USER_START: 'GET_USER_START',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAILURE:'GET_USER_FAILURE',
}